baseURL = "https://unofficial-vra-docs.github.io/"
languageCode = "en-us"
title = "The Unofficial vRealize Automation Docs"
theme = "kraiklyn"

[params]
sidebarColor = "default"

[[menu.shortcuts]]
name = "Contribute"
url = "https://github.com/unofficial-vra-docs/unofficial-vra-docs"
weight = 10

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4