baseURL = "https://unofficial-vra-docs.github.io/"
languageCode = "en-us"
title = "The Unofficial vRealize Automation Docs"
theme = "kraiklyn"

pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsStyle = "github"

[params]
    sidebarColor = "default"
    customCss = ["css/syntax.css"]
[[menu.shortcuts]]
    name = "Contribute"
    url = "https://github.com/unofficial-vra-docs/unofficial-vra-docs"
    weight = 10
