baseURL = "https://vra-examples.github.io/"
languageCode = "en-us"
title = "vRealize Automation Exampes"
theme = "kraiklyn"

pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsStyle = "github"

[params]
    sidebarColor = "default"
    customCss = ["css/syntax.css"]
[[menu.shortcuts]]
    name = "Got an example? Contribute!"
    url = "https://github.com/vra-examples/vra-examples"
    weight = 10
